name: DeployMovieFinderWebsite
on: 
  push: 
    branches: 
      - master
jobs: 
  build: 
    name: "Deploying to surge"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: 
          node-version: 8
      - name: "Install surge"
        run: "npm install -g surge"
      - name: "Install project dependencies"
        run: "npm install"
      - name: "build react application"
        run: "npm run build"
      - name: "Deploy builded app to Surge"
        run: "surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}"


