name: DeployMovieFinderWebsite
on: 
  push: 
    branches: 
      - master
jobs: 
  build: 
    name: "Deploying to surge"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: 
          node-version: 8
      - name: "Install surge"
        run: "npm install -g surge"
      - name: "Install project dependencies"
        run: "npm install"
      - name: "Create settings folder"
        run: "mkdir ./app/src/settings"
      - name: "Create file"
        uses: finnp/create-file-action@1.0.0
        env: 
          FILE_NAME: "settingsFile.js"
          FILE_DATA: "export default { apiKey: '${{ secrets.API_KEY }}' }"
      - name: "Move settings to correct folder"
        run: "mv settingsFile.js ./app/src/settings/index.js"
      - name: "build react application"
        run: "npm run build"
      - name: "Deploy builded app to Surge"
        run: "surge ./app/build --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}"


